// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZakazivanjeTerminaPodaci.Kontekst;

#nullable disable

namespace ZakazivanjeTerminaPodaci.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZakazivanjeTerminaModeli.Dokumentacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumDostavljanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumIzmene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Dostavljeno")
                        .HasColumnType("bit");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrisan")
                        .HasColumnType("bit");

                    b.Property<int>("VrstaDokumentaId")
                        .HasColumnType("int");

                    b.Property<int>("ZahtevZaPasosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VrstaDokumentaId");

                    b.HasIndex("ZahtevZaPasosId");

                    b.ToTable("Dokumentacija");
                });

            modelBuilder.Entity("ZakazivanjeTerminaModeli.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumIzmene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrisan")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("ZakazivanjeTerminaModeli.PodnosilacZahteva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojLicneKarte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DatumIzmene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVazenjaLicneKarte")
                        .HasColumnType("datetime2");

                    b.Property<string>("Drzavljanstvo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MestoRodjenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrisan")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PodnosilacZahteva");
                });

            modelBuilder.Entity("ZakazivanjeTerminaModeli.VrstaDokumenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumIzmene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obavezno")
                        .HasColumnType("bit");

                    b.Property<bool>("Obrisan")
                        .HasColumnType("bit");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VrstaDokumenata");
                });

            modelBuilder.Entity("ZakazivanjeTerminaModeli.ZahtevZaPasos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojZahteva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DatumIzmene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPodnosenja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumTermina")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DokumentacijaKompletna")
                        .HasColumnType("bit");

                    b.Property<bool>("HitanPostupak")
                        .HasColumnType("bit");

                    b.Property<bool>("ImaVazecuLicnuKartu")
                        .HasColumnType("bit");

                    b.Property<decimal>("IznosNaknade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("MestoPodnosenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrisan")
                        .HasColumnType("bit");

                    b.Property<int>("PodnosilacZahtevaId")
                        .HasColumnType("int");

                    b.Property<string>("RazlogIzdavanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazlogOdbijanja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusZahteva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("VremeTermina")
                        .HasColumnType("time");

                    b.Property<string>("VrstaPasosa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("PodnosilacZahtevaId");

                    b.ToTable("ZahteviZaPasos");
                });

            modelBuilder.Entity("ZakazivanjeTerminaModeli.Dokumentacija", b =>
                {
                    b.HasOne("ZakazivanjeTerminaModeli.VrstaDokumenta", "VrstaDokumenta")
                        .WithMany("Dokumentacija")
                        .HasForeignKey("VrstaDokumentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZakazivanjeTerminaModeli.ZahtevZaPasos", "ZahtevZaPasos")
                        .WithMany("Dokumentacija")
                        .HasForeignKey("ZahtevZaPasosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VrstaDokumenta");

                    b.Navigation("ZahtevZaPasos");
                });

            modelBuilder.Entity("ZakazivanjeTerminaModeli.ZahtevZaPasos", b =>
                {
                    b.HasOne("ZakazivanjeTerminaModeli.Korisnik", "Korisnik")
                        .WithMany("ZahteviZaPasos")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZakazivanjeTerminaModeli.PodnosilacZahteva", "PodnosilacZahteva")
                        .WithMany("ZahteviZaPasos")
                        .HasForeignKey("PodnosilacZahtevaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("PodnosilacZahteva");
                });

            modelBuilder.Entity("ZakazivanjeTerminaModeli.Korisnik", b =>
                {
                    b.Navigation("ZahteviZaPasos");
                });

            modelBuilder.Entity("ZakazivanjeTerminaModeli.PodnosilacZahteva", b =>
                {
                    b.Navigation("ZahteviZaPasos");
                });

            modelBuilder.Entity("ZakazivanjeTerminaModeli.VrstaDokumenta", b =>
                {
                    b.Navigation("Dokumentacija");
                });

            modelBuilder.Entity("ZakazivanjeTerminaModeli.ZahtevZaPasos", b =>
                {
                    b.Navigation("Dokumentacija");
                });
#pragma warning restore 612, 618
        }
    }
}
